version: '3'

services:
    revproxy:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./nginx-site.conf:/etc/nginx/conf.d/default.conf:ro

    auth:
        build: auth
        environment:
            - SECRET_KEY=12345678

    upstream:
        image: nginx
